apiVersion: v1
name: rocketchat
version: 3.0.0
appVersion: 3.7.2
description: Prepare to take off with the ultimate chat platform, experience the next level of team communications
keywords:
- chat
- communication
- http
- web
- application
- nodejs
- javascript
- meteor
home: https://rocket.chat/
icon: https://raw.githubusercontent.com/RocketChat/Rocket.Chat.Artwork/master/Logos/icon.svg
sources:
- https://github.com/RocketChat/Docker.Official.Image/
maintainers:
- name: RocketChat
  email: buildmaster@rocket.chat
engine: gotpl
