{{- if .Values.microservices }}
apiVersion: v1
kind: Service
metadata:
  name: nats-svc
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "7777"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
  - name: http
    targetPort: 7777
    port: 7777
  - name: metrics
    targetPort: 8080
    port: 8080
  selector:
    app: nats
{{end}}
