{{- $ingress := .Values.ingress -}}
{{- if $ingress.enabled -}}
{{- if .Values.microservices.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ddp-streamer
{{- with $ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "rocketchat.name" . }}-ddp-streamer
    helm.sh/chart: {{ include "rocketchat.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-ddp-streamer
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
{{- if $ingress.tls }}
  tls:
  {{- range $ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end }}
  {{- end }}
{{- end }}
  rules:
  -
  {{- if .Values.host }}
    host: {{ .Values.host }}
  {{- end }}
    http:
      paths:
      - path: /sockjs
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-ddp-streamer
            port:
              name: http
      - path: /websocket
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-ddp-streamer
            port:
              name: http
{{- end }}
{{- end }}
