name: Update helm chart

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

env:
  HELM_REPO: RocketChat/helm-charts

jobs:
  is-chart-working:
    runs-on: ubuntu-latest
    steps:
      - name: Clone helm chart repository
        uses: actions/checkout@v3
        with:
          path: ./helm-charts
      - name: Clone tests
        uses: actions/checkout@v3
        with:
          repository: debdutdeb/rocket.chat.tests
          path: tests
      - name: Setup k3d
        uses: nolar/setup-k3d-k3s@v1
      - name: Run tests
        shell: bash
        run: |
          sudo apt-get install --no-install-recommends -y jo jq
          export ROCKETCHAT_TAG=${{ inputs.tag }}
          export ROCKETCHAT_CHART_DIR="$(realpath ./helm-charts/rocketchat)"
          cd tests &&
            bash run_k8s.bash

  update-release:
    needs:
      - is-chart-working
    runs-on: ubuntu-latest
    steps:
      - name: Clone helm repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.HELM_REPO }}
          path: ./helm-charts

      - name: Clone helm repo (gh-pages)
        uses: actions/checkout@v2
        with:
          repository: ${{ env.HELM_REPO }}
          ref: gh-pages
          path: ./gh-pages

      - name: Update chart and rocketchat versions
        shell: bash
        id: version
        run: |
          sed -i -r '/^appVersion:/ s/ .+/ ${{ inputs.tag }}/' ./helm-charts/rocketchat/Chart.yaml
          sed -i -r '/^version:/ s/ .+/ ${{ inputs.tag }}/' ./helm-charts/rocketchat/Chart.yaml

      - name: Pull dependencies
        shell: bash
        run: helm dependency update ./helm-charts/rocketchat

      - name: Generate helm package
        shell: bash
        run: helm package ./helm-charts/rocketchat -d gh-pages/charts/

      - name: Re-generate helm index
        run: helm repo index ./gh-pages/

      - name: Push to master
        uses: EndBug/add-and-commit@v7
        with:
          add: "rocketchat/Chart.yaml"
          cwd: helm-charts
          branch: master
          message: "Chore: bump Rocket.Chat and chart version to ${{ inputs.tag }}"
          push: true

      - name: Push to gh-pages
        uses: EndBug/add-and-commit@v7
        with:
          add: "."
          cwd: gh-pages
          branch: gh-pages
          message: "Chore: bump Rocket.Chat and chart version to ${{ inputs.tag }}"
          push: true
